services:
  adameds-inventory:
    build:
      context: ./
      dockerfile: Dockerfile
      no_cache: true
    image: adameds/inventory:dev
    container_name: api-adameds-inventory
    ports:
      - 8088:8088
    restart: always
    networks:
      - inventory-network
    environment:
      INFISICAL_TOKEN: ${INFISICAL_TOKEN}
      API_BASE: ${API_BASE}
      API_VERSION: ${API_VERSION}
    # volumes:
    #   - type: bind
    #     source: /home/engineer/adameds/.env.vault
    #     target: /adameds-inventory/.env.vault
networks:
  inventory-network:
    driver: bridge
